default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: posts_app_development

test:
  <<: *default
  database: posts_app_test

production:
  <<: *default
  database: posts_app_production
  username: posts_app
  password: <%= ENV['POSTS_APP_DATABASE_PASSWORD'] %>
